<?php

declare(strict_types=1);

return [
    'bootstrap_superadmin_email' => env('FANGABASE_BOOTSTRAP_SUPERADMIN_EMAIL'),
    'public_origin' => env('PUBLIC_ORIGIN', 'http://localhost:3000'),
    'cookie_domain' => env('COOKIE_DOMAIN'),
    'cookie_secure' => env('APP_ENV') === 'production',
    'cookie_same_site' => env('COOKIE_SAME_SITE', 'lax'),
    'session_minutes' => (int) env('SESSION_MINUTES', 30),
    'refresh_days' => (int) env('REFRESH_DAYS', 30),
    'verification_minutes' => (int) env('VERIFICATION_MINUTES', 15),
    'password_reset_minutes' => (int) env('PASSWORD_RESET_MINUTES', 15),
    'mail_provider' => env('MAIL_PROVIDER', 'local'),
    'mail' => [
        'sender' => env('MAIL_FROM_ADDRESS', 'noreply@localhost'),
        'resend_api_key' => env('RESEND_API_KEY'),
        'brevo_api_key' => env('BREVO_API_KEY'),
        'smtp_dsn' => env('SMTP_DSN'),
        'max_attempts' => (int) env('MAIL_MAX_ATTEMPTS', 8),
        'lease_seconds' => (int) env('MAIL_LEASE_SECONDS', 60),
    ],
    'google' => [
        'client_id' => env('GOOGLE_CLIENT_ID'),
        'client_secret' => env('GOOGLE_CLIENT_SECRET'),
        'redirect_uri' => env('GOOGLE_REDIRECT_URI'),
        'state_minutes' => (int) env('GOOGLE_STATE_MINUTES', 10),
        'allowed_return_paths' => array_values(array_filter(explode(',', (string) env('GOOGLE_ALLOWED_RETURN_PATHS', '/,/dashboard')))),
    ],
    'payments' => [
        'checkout_minutes' => (int) env('PAYMENT_CHECKOUT_MINUTES', 30),
        'allowed_return_paths' => array_values(array_filter(explode(',', (string) env('PAYMENT_ALLOWED_RETURN_PATHS', '/billing,/checkout/complete')))),
        'stripe' => ['enabled' => filter_var(env('STRIPE_ENABLED', false), FILTER_VALIDATE_BOOL), 'secret_key' => env('STRIPE_SECRET_KEY'), 'webhook_secret' => env('STRIPE_WEBHOOK_SECRET')],
        'fedapay' => ['enabled' => filter_var(env('FEDAPAY_ENABLED', false), FILTER_VALIDATE_BOOL), 'secret_key' => env('FEDAPAY_SECRET_KEY'), 'base_url' => env('FEDAPAY_BASE_URL', 'https://sandbox-api.fedapay.com')],
        'orange_money_ml' => [
            'enabled' => filter_var(env('ORANGE_MONEY_ENABLED', false), FILTER_VALIDATE_BOOL),
            'environment' => env('ORANGE_MONEY_ENVIRONMENT', 'sandbox'),
            'country' => env('ORANGE_MONEY_COUNTRY', 'ML'),
            'currency' => env('ORANGE_MONEY_CURRENCY', 'XOF'),
            'oauth_token_url' => env('ORANGE_MONEY_OAUTH_TOKEN_URL', ''),
            'api_base_url' => env('ORANGE_MONEY_API_BASE_URL', ''),
            'client_id' => env('ORANGE_MONEY_CLIENT_ID', ''),
            'client_secret' => env('ORANGE_MONEY_CLIENT_SECRET', ''),
            'merchant_account' => env('ORANGE_MONEY_MERCHANT_ACCOUNT', ''),
            'merchant_code' => env('ORANGE_MONEY_MERCHANT_CODE', ''),
            'merchant_key' => env('ORANGE_MONEY_MERCHANT_KEY', ''),
            'return_url' => env('ORANGE_MONEY_RETURN_URL', ''),
            'cancel_url' => env('ORANGE_MONEY_CANCEL_URL', ''),
            'notification_url' => env('ORANGE_MONEY_NOTIFICATION_URL', ''),
            'timeout_seconds' => (int) env('ORANGE_MONEY_HTTP_TIMEOUT_SECONDS', 15),
            'simulator_scenario' => env('ORANGE_MONEY_SIMULATOR_SCENARIO', 'pending'),
        ],
    ],
    'withdrawals' => [
        'minimum_minor' => (int) env('WITHDRAWAL_MINIMUM_MINOR', 1000), 'maximum_minor' => (int) env('WITHDRAWAL_MAXIMUM_MINOR', 1000000),
        'currencies' => array_values(array_filter(explode(',', (string) env('WITHDRAWAL_CURRENCIES', 'XOF')))), 'rate_limit' => (int) env('WITHDRAWAL_RATE_LIMIT', 5),
        'lease_seconds' => (int) env('WITHDRAWAL_LEASE_SECONDS', 60), 'max_attempts' => (int) env('WITHDRAWAL_MAX_ATTEMPTS', 8),
        'callback_secrets' => [],
    ],
];
