import type { FangaBaseConfig } from "./config.js";

export type DeploymentFile = { path: string; content: string };

const header =
  "# Generated by FangaBase. Safe to replace only through the CLI.\n";

function familyOf(
  config: FangaBaseConfig,
): "cloud" | "vps" | "shared" | "hybrid" {
  if (config.deployment) return config.deployment.family;
  if (config.architecture.target === "cloud_vercel") return "cloud";
  if (config.architecture.target === "shared_laravel") return "shared";
  if (config.architecture.target === "hybrid") return "hybrid";
  return "vps";
}

function env(config: FangaBaseConfig, family: string): string {
  const hybrid = family === "hybrid";
  const nextBackend = config.architecture.backend === "next";
  const orangeMoneyMl = config.payments.providers.includes("orange_money_ml")
    ? `ORANGE_MONEY_ENABLED=true
ORANGE_MONEY_ENVIRONMENT=sandbox
ORANGE_MONEY_COUNTRY=ML
ORANGE_MONEY_CURRENCY=XOF
ORANGE_MONEY_OAUTH_TOKEN_URL=
ORANGE_MONEY_API_BASE_URL=
ORANGE_MONEY_CLIENT_ID=
ORANGE_MONEY_CLIENT_SECRET=
ORANGE_MONEY_MERCHANT_ACCOUNT=
ORANGE_MONEY_MERCHANT_CODE=
ORANGE_MONEY_MERCHANT_KEY=
ORANGE_MONEY_RETURN_URL=https://${hybrid ? "api" : "app"}.example.invalid/api/payments/orange-money-ml/return
ORANGE_MONEY_CANCEL_URL=https://${hybrid ? "api" : "app"}.example.invalid/api/payments/orange-money-ml/cancel
ORANGE_MONEY_NOTIFICATION_URL=https://${hybrid ? "api" : "app"}.example.invalid/api/webhooks/orange-money-ml
ORANGE_MONEY_HTTP_TIMEOUT_SECONDS=15
`
    : "";
  return `${header}APP_ENV=production
APP_URL=https://app.example.invalid
APP_VERSION=release-id
DATABASE_URL=inject-pooled-runtime-url
${nextBackend ? "DATABASE_DIRECT_URL=inject-direct-migration-url\nSESSION_SECRET=inject-at-runtime\n" : ""}
MAIL_PROVIDER=${config.email.provider}
STORAGE_PROVIDER=${config.storage.provider}
QUEUE_PROVIDER=${config.queue.provider}
${hybrid ? "BACKEND_PUBLIC_URL=https://api.example.invalid\nFRONTEND_ALLOWED_ORIGINS=https://app.example.invalid\nSESSION_SECURE_COOKIE=true\nSESSION_SAME_SITE=none\n" : ""}${orangeMoneyMl}# Replace every example.invalid value and inject secrets outside Git.
`;
}

const recovery = `${header}# Recovery
Run \`fangabase backup --config fangabase.config.yaml --target <directory> --dry-run\` first.
Use an explicit target, encrypted storage and configured retention. A restore requires
\`--environment\`, \`--confirm\` and an integrity check. Managed databases still require
provider snapshots and an independently tested export. Never run concurrent migrations;
acquire the platform deployment lock, back up first, then deploy additive migrations.
Rollback code independently; destructive schema rollback is not promised.
`;

const smoke = `${header}# Post-deployment smoke test
Run \`fangabase smoke --url https://api.example.invalid --frontend https://app.example.invalid\`.
The test is read-only: liveness, readiness, version and redaction are checked without
sending email, creating data or mutating finance.
`;

export function deploymentFiles(config: FangaBaseConfig): DeploymentFile[] {
  const family = familyOf(config);
  const common: DeploymentFile[] = [
    { path: ".env.production.example", content: env(config, family) },
    { path: "README.md", content: runbook(config, family) },
    { path: "SMOKE.md", content: smoke },
    { path: "RECOVERY.md", content: recovery },
    ...(config.payments.providers.includes("orange_money_ml")
      ? [
          {
            path: "ORANGE-MONEY-MALI.md",
            content: orangeMoneyMlGuide(config, family),
          },
        ]
      : []),
    ...(config.architecture.frontend === "react" ? reactFrontend() : []),
  ];
  if (family === "cloud") {
    return [
      ...common,
      {
        path: "vercel.json",
        content: `${JSON.stringify({ framework: "nextjs", buildCommand: "pnpm --filter @fangabase/web build", crons: [{ path: "/api/cron", schedule: "*/5 * * * *" }] }, null, 2)}\n`,
      },
    ];
  }
  if (family === "shared") {
    return [
      ...common,
      {
        path: "cron.example",
        content: `${header}* * * * * php /path/to/artisan schedule:run\n* * * * * php /path/to/artisan fangabase:outbox-work --once --limit=25\n`,
      },
      {
        path: "public-root.md",
        content: `${header}Point the document root to apps/server/public. If the host fixes public_html, keep application and secrets above it and expose only Laravel public files. Never copy .env into public_html.\n`,
      },
    ];
  }
  const serverFiles: DeploymentFile[] = [
    {
      path: "systemd/fangabase-web.service",
      content:
        config.architecture.backend === "laravel"
          ? systemd("web", "php artisan serve --host=127.0.0.1 --port=8000")
          : systemd("web", "pnpm --filter @fangabase/web start"),
    },
    ...(config.architecture.backend === "laravel"
      ? [
          {
            path: "systemd/fangabase-worker.service",
            content: systemd("worker", "php artisan fangabase:outbox-work"),
          },
          {
            path: "systemd/fangabase-scheduler.service",
            content: systemd("scheduler", "php artisan schedule:work"),
          },
        ]
      : [
          {
            path: "systemd/fangabase-worker.service",
            content: systemd(
              "worker",
              "pnpm --filter @fangabase/backend-next worker",
            ),
          },
          {
            path: "systemd/fangabase-scheduler.service",
            content: systemd(
              "scheduler",
              "pnpm --filter @fangabase/backend-next scheduler",
            ),
          },
        ]),
    {
      path: "nginx/fangabase.conf.example",
      content: `${header}server { listen 443 ssl; server_name example.invalid; location / { proxy_pass http://127.0.0.1:${config.architecture.backend === "laravel" ? "8000" : "3000"}; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header Host $host; } }\n`,
    },
  ];
  if (family === "hybrid") {
    return [
      ...common,
      ...serverFiles,
      {
        path: "frontend/vercel.json",
        content: `${JSON.stringify({ framework: "nextjs", buildCommand: "pnpm --filter @fangabase/web build" }, null, 2)}\n`,
      },
    ];
  }
  const files = [...common, ...serverFiles];
  if (config.deployment?.docker) files.push(...dockerFiles(config));
  return files;
}

function orangeMoneyMlGuide(config: FangaBaseConfig, family: string): string {
  const authority =
    family === "hybrid" || config.architecture.backend === "laravel"
      ? "Laravel"
      : "Next.js";
  const operations =
    family === "shared"
      ? "Planifiez le rapprochement et l'Outbox avec le cron borné généré ; aucun daemon permanent n'est requis."
      : "Exécutez le worker et le rapprochement selon le profil généré.";
  return `${header}# Orange Money Mali

Cette intégration est facultative et spécifique au contrat Orange Money Mali.
Le backend d'autorité est ${authority}. La génération des variables ne crée
pas un compte marchand et ne valide ni une sandbox officielle ni la production.

1. Terminez la génération du projet.
2. Devenez marchand Orange Money auprès d'Orange Mali et terminez la conformité KYA.
3. Obtenez du contrat marchand les URL, identifiants et paramètres applicables.
4. Renseignez les variables ORANGE_MONEY_* dans l'hébergeur, jamais dans Git.
5. Configurez les trois URL HTTPS publiques générées.
6. Exécutez les migrations.
7. Testez d'abord avec ORANGE_MONEY_ENVIRONMENT=simulator.
8. Effectuez ensuite la recette sandbox officielle si votre compte l'autorise.
9. Vérifiez notifications, statuts, montants et devise XOF.
10. Passez en production uniquement après validation écrite d'Orange Mali.

${operations}

Les routes return/cancel ne sont jamais autoritaires. Si le contrat ne fournit
pas de signature vérifiable, la notification déclenche obligatoirement une
interrogation serveur-à-serveur du statut. Ne publiez jamais les clés, tokens
OAuth, pay tokens, notification tokens, signatures ou certificats.
`;
}

function reactFrontend(): DeploymentFile[] {
  return [
    {
      path: "frontend/package.json",
      content: `${JSON.stringify(
        {
          name: "fangabase-react-headless",
          private: true,
          type: "module",
          scripts: { dev: "vite", build: "tsc && vite build" },
          dependencies: { react: "19.1.0", "react-dom": "19.1.0" },
          devDependencies: {
            "@vitejs/plugin-react": "4.6.0",
            vite: "7.0.0",
            typescript: "5.8.3",
            "@types/react": "19.1.8",
            "@types/react-dom": "19.1.6",
          },
        },
        null,
        2,
      )}\n`,
    },
    {
      path: "frontend/index.html",
      content:
        '<div id="root"></div><script type="module" src="/src.tsx"></script>\n',
    },
    {
      path: "frontend/src.tsx",
      content: `import React from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

const origin = import.meta.env.VITE_API_ORIGIN || "";
async function api(path: string, init: RequestInit = {}) {
  const csrf = document.cookie.split("; ").find((item) => item.startsWith("fangabase_csrf="))?.split("=")[1];
  const response = await fetch(origin + path, {
    ...init,
    credentials: "include",
    headers: { "Content-Type": "application/json", ...(csrf ? { "X-CSRF-Token": decodeURIComponent(csrf) } : {}), ...init.headers },
  });
  const body = await response.json();
  if (!response.ok) throw new Error(body?.error?.code || "REQUEST_FAILED");
  return body;
}

function App() {
  const [result, setResult] = React.useState("Non vérifié");
  return <main><h1>Application technique</h1><p>{result}</p><button onClick={() => api("/api/health").then(() => setResult("Backend disponible")).catch((error) => setResult(error.message))}>Vérifier</button></main>;
}
createRoot(document.getElementById("root")!).render(<App />);
`,
    },
    {
      path: "frontend/style.css",
      content:
        "body{font:16px system-ui;line-height:1.5;margin:2rem;max-width:48rem}button{font:inherit;padding:.5rem}\n",
    },
    {
      path: "frontend/.env.example",
      content: "VITE_API_ORIGIN=https://api.example.invalid\n",
    },
  ];
}

function systemd(name: string, command: string): string {
  const directory = command.startsWith("pnpm")
    ? "/srv/fangabase"
    : "/srv/fangabase/apps/server";
  return `${header}[Unit]\nDescription=FangaBase ${name}\nAfter=network.target\n[Service]\nUser=fangabase\nWorkingDirectory=${directory}\nEnvironmentFile=/etc/fangabase/server.env\nExecStart=/usr/bin/${command}\nRestart=on-failure\nTimeoutStopSec=30\nNoNewPrivileges=true\n[Install]\nWantedBy=multi-user.target\n`;
}

function dockerFiles(config: FangaBaseConfig): DeploymentFile[] {
  if (config.architecture.backend === "laravel") {
    return [
      {
        path: "docker/Dockerfile",
        content: `${header}FROM composer:2.8.9 AS vendor
WORKDIR /app
COPY apps/server/composer.json apps/server/composer.lock ./
RUN composer install --no-dev --no-interaction --prefer-dist --no-scripts
FROM php:8.2.12-cli-alpine3.21
RUN addgroup -S fangabase && adduser -S fangabase -G fangabase
WORKDIR /app
COPY --from=vendor /app/vendor ./vendor
COPY apps/server .
USER fangabase
CMD ["php","artisan","serve","--host=0.0.0.0","--port=8000"]
`,
      },
      {
        path: "docker/compose.production.yml",
        content: `${header}services:
  web:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    restart: unless-stopped
    env_file: /run/secrets/fangabase.env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8000/up"]
      interval: 30s
      timeout: 5s
      retries: 3
  worker:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    command: ["php", "artisan", "fangabase:outbox-work"]
    env_file: /run/secrets/fangabase.env
    stop_grace_period: 30s
`,
      },
    ];
  }
  return [
    {
      path: "docker/Dockerfile",
      content: `${header}FROM node:22.17.0-alpine3.21 AS build\nWORKDIR /app\nCOPY . .\nRUN corepack enable && pnpm install --frozen-lockfile && pnpm build\nUSER node\nCMD ["pnpm","--filter","@fangabase/web","start"]\n`,
    },
    {
      path: "docker/compose.production.yml",
      content: `${header}services:\n  web:\n    build:\n      context: ../..\n      dockerfile: deployment/docker/Dockerfile\n    restart: unless-stopped\n    env_file: /run/secrets/fangabase.env\n    healthcheck:\n      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/api/health"]\n      interval: 30s\n      timeout: 5s\n      retries: 3\n`,
    },
  ];
}

function runbook(config: FangaBaseConfig, family: string): string {
  const migration =
    config.architecture.backend === "next"
      ? "pnpm --filter @fangabase/backend-next migrate"
      : "php apps/server/artisan migrate --force";
  const limitations =
    family === "cloud"
      ? "Laravel is not deployed on Vercel by this profile. Use Hybrid when Laravel is the backend. Serverless runtimes cannot host persistent workers."
      : family === "shared"
        ? "No Docker, root access, systemd or permanent daemon is assumed. Queue and Outbox work runs in short bounded cron batches."
        : family === "hybrid"
          ? "HTTPS is mandatory. Configure exact CORS origins, CSRF trusted origins, secure HttpOnly cookies and route callbacks/webhooks to Laravel."
          : "Provision HTTPS, trusted proxies, log rotation, one scheduler, distinct workers and database backups.";
  return `${header}# ${family} deployment\n\nRequired: ${config.database.engine}, runtime secrets, HTTPS, migrations and health checks.\nOptional: Redis-compatible cache, remote private storage and remote email adapter.\n\nBuild: \`pnpm install --frozen-lockfile && pnpm build\`\nMigrate once under a deployment lock: \`${migration}\`\nHealth: \`/api/health\`; readiness: \`/api/readiness\`.\n\n${limitations}\n\nSet file permissions to the service user, expose only proxy ports, redact logs, inject secrets at runtime and configure backup retention.\n`;
}
