import type { FangaBaseConfig } from "./config.js";

export type DeploymentFile = { path: string; content: string };

const header =
  "# Generated by FangaBase. Safe to replace only through the CLI.\n";

function familyOf(
  config: FangaBaseConfig,
): "cloud" | "vps" | "shared" | "hybrid" {
  if (config.deployment) return config.deployment.family;
  if (config.architecture.target === "cloud_vercel") return "cloud";
  if (config.architecture.target === "shared_laravel") return "shared";
  if (config.architecture.target === "hybrid") return "hybrid";
  return "vps";
}

function env(config: FangaBaseConfig, family: string): string {
  const hybrid = family === "hybrid";
  return `${header}APP_ENV=production
APP_URL=https://app.example.invalid
APP_VERSION=release-id
DATABASE_URL=inject-at-runtime
MAIL_PROVIDER=${config.email.provider}
STORAGE_PROVIDER=${config.storage.provider}
QUEUE_PROVIDER=${config.queue.provider}
${hybrid ? "BACKEND_PUBLIC_URL=https://api.example.invalid\nFRONTEND_ALLOWED_ORIGINS=https://app.example.invalid\nSESSION_SECURE_COOKIE=true\nSESSION_SAME_SITE=none\n" : ""}# Replace every example.invalid value and inject secrets outside Git.
`;
}

const recovery = `${header}# Recovery
Run \`fangabase backup --config fangabase.config.yaml --target <directory> --dry-run\` first.
Use an explicit target, encrypted storage and configured retention. A restore requires
\`--environment\`, \`--confirm\` and an integrity check. Managed databases still require
provider snapshots and an independently tested export. Never run concurrent migrations;
acquire the platform deployment lock, back up first, then deploy additive migrations.
Rollback code independently; destructive schema rollback is not promised.
`;

const smoke = `${header}# Post-deployment smoke test
Run \`fangabase smoke --url https://api.example.invalid --frontend https://app.example.invalid\`.
The test is read-only: liveness, readiness, version and redaction are checked without
sending email, creating data or mutating finance.
`;

export function deploymentFiles(config: FangaBaseConfig): DeploymentFile[] {
  const family = familyOf(config);
  const common: DeploymentFile[] = [
    { path: ".env.production.example", content: env(config, family) },
    { path: "README.md", content: runbook(config, family) },
    { path: "SMOKE.md", content: smoke },
    { path: "RECOVERY.md", content: recovery },
  ];
  if (family === "cloud") {
    return [
      ...common,
      {
        path: "vercel.json",
        content: `${JSON.stringify({ framework: "nextjs", buildCommand: "pnpm --filter @fangabase/web build", crons: [] }, null, 2)}\n`,
      },
    ];
  }
  if (family === "shared") {
    return [
      ...common,
      {
        path: "cron.example",
        content: `${header}* * * * * php /path/to/artisan schedule:run\n* * * * * php /path/to/artisan fangabase:outbox-work --once --limit=25\n`,
      },
      {
        path: "public-root.md",
        content: `${header}Point the document root to apps/server/public. If the host fixes public_html, keep application and secrets above it and expose only Laravel public files. Never copy .env into public_html.\n`,
      },
    ];
  }
  const serverFiles: DeploymentFile[] = [
    {
      path: "systemd/fangabase-web.service",
      content:
        config.architecture.backend === "laravel"
          ? systemd("web", "php artisan serve --host=127.0.0.1 --port=8000")
          : systemd("web", "pnpm --filter @fangabase/web start"),
    },
    ...(config.architecture.backend === "laravel"
      ? [
          {
            path: "systemd/fangabase-worker.service",
            content: systemd("worker", "php artisan fangabase:outbox-work"),
          },
          {
            path: "systemd/fangabase-scheduler.service",
            content: systemd("scheduler", "php artisan schedule:work"),
          },
        ]
      : []),
    {
      path: "nginx/fangabase.conf.example",
      content: `${header}server { listen 443 ssl; server_name example.invalid; location / { proxy_pass http://127.0.0.1:${config.architecture.backend === "laravel" ? "8000" : "3000"}; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header Host $host; } }\n`,
    },
  ];
  if (family === "hybrid") {
    return [
      ...common,
      ...serverFiles,
      {
        path: "frontend/vercel.json",
        content: `${JSON.stringify({ framework: "nextjs", buildCommand: "pnpm --filter @fangabase/web build" }, null, 2)}\n`,
      },
    ];
  }
  const files = [...common, ...serverFiles];
  if (config.deployment?.docker) files.push(...dockerFiles(config));
  return files;
}

function systemd(name: string, command: string): string {
  const directory = command.startsWith("pnpm")
    ? "/srv/fangabase"
    : "/srv/fangabase/apps/server";
  return `${header}[Unit]\nDescription=FangaBase ${name}\nAfter=network.target\n[Service]\nUser=fangabase\nWorkingDirectory=${directory}\nEnvironmentFile=/etc/fangabase/server.env\nExecStart=/usr/bin/${command}\nRestart=on-failure\nTimeoutStopSec=30\nNoNewPrivileges=true\n[Install]\nWantedBy=multi-user.target\n`;
}

function dockerFiles(config: FangaBaseConfig): DeploymentFile[] {
  if (config.architecture.backend === "laravel") {
    return [
      {
        path: "docker/Dockerfile",
        content: `${header}FROM composer:2.8.9 AS vendor
WORKDIR /app
COPY apps/server/composer.json apps/server/composer.lock ./
RUN composer install --no-dev --no-interaction --prefer-dist --no-scripts
FROM php:8.2.12-cli-alpine3.21
RUN addgroup -S fangabase && adduser -S fangabase -G fangabase
WORKDIR /app
COPY --from=vendor /app/vendor ./vendor
COPY apps/server .
USER fangabase
CMD ["php","artisan","serve","--host=0.0.0.0","--port=8000"]
`,
      },
      {
        path: "docker/compose.production.yml",
        content: `${header}services:
  web:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    restart: unless-stopped
    env_file: /run/secrets/fangabase.env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8000/up"]
      interval: 30s
      timeout: 5s
      retries: 3
  worker:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    command: ["php", "artisan", "fangabase:outbox-work"]
    env_file: /run/secrets/fangabase.env
    stop_grace_period: 30s
`,
      },
    ];
  }
  return [
    {
      path: "docker/Dockerfile",
      content: `${header}FROM node:22.17.0-alpine3.21 AS build\nWORKDIR /app\nCOPY . .\nRUN corepack enable && pnpm install --frozen-lockfile && pnpm build\nUSER node\nCMD ["pnpm","--filter","@fangabase/web","start"]\n`,
    },
    {
      path: "docker/compose.production.yml",
      content: `${header}services:\n  web:\n    build:\n      context: ../..\n      dockerfile: deployment/docker/Dockerfile\n    restart: unless-stopped\n    env_file: /run/secrets/fangabase.env\n    healthcheck:\n      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/api/health"]\n      interval: 30s\n      timeout: 5s\n      retries: 3\n`,
    },
  ];
}

function runbook(config: FangaBaseConfig, family: string): string {
  const limitations =
    family === "cloud"
      ? "Laravel is not deployed on Vercel by this profile. Use Hybrid when Laravel is the backend. Serverless runtimes cannot host persistent workers."
      : family === "shared"
        ? "No Docker, root access, systemd or permanent daemon is assumed. Queue and Outbox work runs in short bounded cron batches."
        : family === "hybrid"
          ? "HTTPS is mandatory. Configure exact CORS origins, CSRF trusted origins, secure HttpOnly cookies and route callbacks/webhooks to Laravel."
          : "Provision HTTPS, trusted proxies, log rotation, one scheduler, distinct workers and database backups.";
  return `${header}# ${family} deployment\n\nRequired: ${config.database.engine}, runtime secrets, HTTPS, migrations and health checks.\nOptional: Redis-compatible cache, remote private storage and remote email adapter.\n\nBuild: \`pnpm install --frozen-lockfile && pnpm build\`\nMigrate once under a deployment lock: \`php apps/server/artisan migrate --force\`\nHealth: \`/api/health\`; readiness: \`/api/readiness\`; liveness: \`/up\`.\n\n${limitations}\n\nSet file permissions to the service user, expose only proxy ports, redact logs, inject secrets at runtime and configure backup retention.\n`;
}
