name: ci-sast
on: [push, pull_request]
permissions: { contents: read, security-events: write }
jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions: { contents: read, security-events: write, packages: read }
    strategy:
      matrix: { language: [javascript-typescript] }
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: github/codeql-action/init@4187e74d05793876e9989daffde9c3e66b4acd07 # v3
        with: { languages: "${{ matrix.language }}" }
      - uses: github/codeql-action/analyze@4187e74d05793876e9989daffde9c3e66b4acd07 # v3
  secrets:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { fetch-depth: 0 }
      - uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
